# Generated by Django 4.2.6 on 2023-12-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='work_type',
            field=models.CharField(default='Missing', max_length=255),
            preserve_default=False,
        ),
    ]
